[tool.poetry]
name = "gainy-compute"
version = "0.1.0"
description = "Everything related to data computations and ML models in Python"
authors = ["Vasilii Khomutov <vasilii@gainy.app>"]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.3.4"
sklearn = "^0.0"
nltk = "^3.6.5"
geotext = "^0.4.0"
geonamescache = "^1.3.0"
annoy = "^1.17.0"
joblib = "^1.1.0"
pyahocorasick = "^1.4.2"
stop-words = "^2018.7.23"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
