[tool.poetry]
name = "gainy-compute"
version = "0.1.4"
description = "All stuff related to data computations and ML models in Python"
authors = ["Vasilii Khomutov <vasilii@gainy.app>"]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.3.4"
sklearn = "^0.0"
nltk = "^3.6.5"
annoy = "^1.17.0"
psycopg2 = "^2.9.2"
SQLAlchemy = "^1.4.28"
mlflow = "^1.22.0"
pyarrow = "^6.0.1"
boto3 = "^1.20.24"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.1.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
gainy_industry_assignment = "gainy_compute.industries.runner:cli"
