ATTRIBUTE_USER_EMAIL = "user_email"
ATTRIBUTE_INTERESTS = "interests"
ATTRIBUTE_CATEGORIES = "categories"
ATTRIBUTE_MATCH_SCORE_CREATED = "ms_created"
ATTRIBUTE_DW_ACCOUNT_OPENED = "dw_account_opened"
ATTRIBUTE_FUNDING_ACC_CONNECTED = "funding_acc_connected"
ATTRIBUTE_PRODUCT_TYPE_PURCHASED = "product_type_purchased"  # edited
ATTRIBUTE_TOTAL_INVESTED_TTFS = "total_invested_ttfs"  # edited
ATTRIBUTE_TOTAL_INVESTED_TICKERS = "total_invested_tickers"  # edited
ATTRIBUTE_TOTAL_WISHLIST_TTFS = "total_wishlist_ttfs"  # edited
ATTRIBUTE_TOTAL_WISHLIST_TICKER = "total_wishlist_ticker"
ATTRIBUTE_TOTAL_TRANSACTIONS = "total_transactions"
ATTRIBUTE_TOTAL_DEPOSITS = "total_deposits"
ATTRIBUTE_TOTAL_WITHDRAWS = "total_withdraws"  # edited
ATTRIBUTE_TOTAL_INVESTS = "total_invests"
ATTRIBUTE_TOTAL_SELLS = "total_sells"
ATTRIBUTE_TOTAL_TRADES = "total_trades"
ATTRIBUTE_TOTAL_AMOUNT_DEPOSIT = "total_amount_deposit"
ATTRIBUTE_TOTAL_AMOUNT_INVEST = "total_amount_invest"
ATTRIBUTE_TOTAL_AMOUNT_SELL = "total_amount_sell"
ATTRIBUTE_FIRST_PURCHASED_DATE = "first_purchased_date"  # edited
ATTRIBUTE_FIRST_SELL_DATE = "first_sell_date"
ATTRIBUTE_LAST_PURCHASED_DATE = "last_purchased_date"
ATTRIBUTE_LAST_SELL_DATE = "last_sell_date"
ATTRIBUTE_KYC_INVEST_EXPERIENCE = "kyc_invest_experience"  # edited
ATTRIBUTE_KYC_INCOME = "kyc_income"
ATTRIBUTE_KYC_NET_WORTH = "kyc_net_worth"
ATTRIBUTE_KYC_INVEST_HORIZONT = "kyc_invest_horizont"
ATTRIBUTE_KYC_RISK_TOLERANCE = "kyc_risk_tolerance"  # edited
ATTRIBUTE_KYC_EMPLOYMENT_STATUS = "kyc_employment_status"
ATTRIBUTE_KYC_SOURCE_OF_FUNDS = "kyc_source_of_funds"
