import os

DRIVEWEALTH_APP_KEY = os.getenv("DRIVEWEALTH_APP_KEY")
DRIVEWEALTH_WLP_ID = os.getenv("DRIVEWEALTH_WLP_ID")
DRIVEWEALTH_PARENT_IBID = os.getenv("DRIVEWEALTH_PARENT_IBID")
DRIVEWEALTH_RIA_ID = os.getenv("DRIVEWEALTH_RIA_ID")
DRIVEWEALTH_RIA_PRODUCT_ID = os.getenv("DRIVEWEALTH_RIA_PRODUCT_ID")
DRIVEWEALTH_API_USERNAME = os.getenv("DRIVEWEALTH_API_USERNAME")
DRIVEWEALTH_API_PASSWORD = os.getenv("DRIVEWEALTH_API_PASSWORD")
DRIVEWEALTH_API_URL = os.getenv("DRIVEWEALTH_API_URL")
DRIVEWEALTH_IS_UAT = os.getenv("DRIVEWEALTH_IS_UAT", "true") != "false"
DRIVEWEALTH_HOUSE_ACCOUNT_NO = os.getenv("DRIVEWEALTH_HOUSE_ACCOUNT_NO")
