name: "pytest"
description: "An action to run pytest"
branding:
  icon: "check-circle"
  color: "blue"
inputs:
  python-version:
    description: "The version of python to run tests with"
    required: false
    default: "3.9"
runs:
  using: "composite"
  steps:
    - name: Setup Python
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}

    - name: Set up
      run: |
        pip install poetry
        make install

    - name: Run tests
      id: test
      run: make test 2>&1