name: "Main"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
# todo enable
#  style-check:
#    name: "Style Check"
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#
#      - name: YAPF install
#        run: pip3 install yapf toml
#
#      - name: YAPF
#        run: make style-check

  test:
    name: "Run tests"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.9 ]
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run tests
        id: test
        continue-on-error: true
        run: make test 2>&1

      - name: Tests Status
        if: steps.test.outcome == 'failure'
        run: make test-clean && exit 1
