name: "Release"

on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: 'Pre-release'
        required: true
        type: boolean

jobs:
  publish:
    name: "Build & Publish"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        run: |
          pip install poetry
          make install

      - name: Build
        run: make build

      - name: Publish
        run: |
          export AWS_ACCESS_KEY_ID=A && aws --version
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PWD }}



