name: "Release"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: "Run tests"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.9 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unit tests
        uses: ./.github/actions/unit_tests
        with:
          python-version: ${{ matrix.python-version }}

  publish:
    name: "Build & Publish"
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Publish
        if: startsWith(github.ref, 'refs/tags/')
        run: make publish
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}



