name: "Release"

on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: 'Pre-release'
        required: true
        type: boolean

jobs:
  publish:
    name: "Build & Publish"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        run: |
          pip install poetry
          make install
        shell: bash

      - name: Build
        run: make build

      - name: Publish
        run: |
          poetry config repositories.gainy $(shell aws codeartifact get-repository-endpoint --domain gainy-app --repository gainy-app --format pypi --query repositoryEndpoint --output text)
          poetry publish -n -u aws -p $(shell aws codeartifact get-authorization-token --domain gainy-app --query authorizationToken --output text) -r gainy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}



