name: "Release"

on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: 'Pre-release'
        required: true
        type: boolean

jobs:
  test:
    uses: ./.github/workflows/test.yml

  publish:
    name: "Build & Publish"
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Poetry
        run: |
          pip install poetry
          make install

      - name: Bump Version
        if: github.event.inputs.prerelease
        run: poetry version $(poetry version -s)-alpha.$(date '+%s')

      - name: Build
        run: make build

      - name: Publish
        run: make publish
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

      - name: Get Version
        run: echo RELEASE_VERSION=$(poetry version -s) >> $GITHUB_ENV

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.RELEASE_VERSION }}
          release_name: Release v${{ env.RELEASE_VERSION }}
          prerelease: github.event.inputs.prerelease
