name: "Test"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    name: "Run tests"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.9 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unit tests
        uses: ./.github/actions/unit_tests
        with:
          python-version: ${{ matrix.python-version }}
