name: "Test"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.8, 3.9 ]
    steps:
      - name: "Unit tests"
        uses: ./.github/actions/unit_tests
        with:
          python-version: ${{ matrix.python-version }}

#
#  publish:
#    name: "Publish"
#    runs-on: ubuntu-latest
#    needs: test
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#
#      - name: Authorize
#        if: startsWith(github.ref, 'refs/tags/')
#        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 217303665077.dkr.ecr.us-east-1.amazonaws.com
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#
#      - name: Build
#        run: make build
#
#      - name: Publish
#        if: startsWith(github.ref, 'refs/tags/')
#        run: make publish


