name: "Tests"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: "Unit tests"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.8 ]
        poetry-version: [ 1.1.12 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up
        run: |
          pip install poetry==${{ matrix.poetry-version }}
          make install

      - name: Run tests
        id: test
        continue-on-error: true
        run: |
          cd ..
          make test 2>&1

      - name: Tests Status
        if: steps.test.outcome == 'failure'
        run: exit 1

